/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminAccount = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ServiceStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'status' : ServiceStatus,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'connectionDate' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyFee' : IDL.Float64,
  'packageId' : IDL.Nat,
  'dueAmount' : IDL.Float64,
});
export const Node = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'connectedCustomers' : IDL.Nat,
  'location' : IDL.Text,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'speed' : IDL.Text,
  'monthlyPrice' : IDL.Float64,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'date' : Time,
  'note' : IDL.Text,
  'year' : IDL.Nat,
  'customerId' : IDL.Nat,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminAccounts' : IDL.Func([], [IDL.Vec(AdminAccount)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getNode' : IDL.Func([IDL.Nat], [Node], ['query']),
  'getNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
  'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAdminAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'removeAdminAccount' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminAccount = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ServiceStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'status' : ServiceStatus,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'connectionDate' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyFee' : IDL.Float64,
    'packageId' : IDL.Nat,
    'dueAmount' : IDL.Float64,
  });
  const Node = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'connectedCustomers' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'speed' : IDL.Text,
    'monthlyPrice' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'date' : Time,
    'note' : IDL.Text,
    'year' : IDL.Nat,
    'customerId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminAccounts' : IDL.Func([], [IDL.Vec(AdminAccount)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getNode' : IDL.Func([IDL.Nat], [Node], ['query']),
    'getNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
    'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAdminAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'removeAdminAccount' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };