/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAccount { 'name' : string, 'email' : string }
export interface Customer {
  'id' : bigint,
  'status' : ServiceStatus,
  'area' : string,
  'name' : string,
  'email' : string,
  'connectionDate' : Time,
  'address' : string,
  'phone' : string,
  'monthlyFee' : number,
  'packageId' : bigint,
  'dueAmount' : number,
}
export interface Node {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'connectedCustomers' : bigint,
  'location' : string,
}
export interface Package {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'speed' : string,
  'monthlyPrice' : number,
}
export interface Payment {
  'id' : bigint,
  'month' : bigint,
  'paymentMethod' : string,
  'date' : Time,
  'note' : string,
  'year' : bigint,
  'customerId' : bigint,
  'amount' : number,
}
export type ServiceStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'suspended' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminAccount' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminAccounts' : ActorMethod<[], Array<AdminAccount>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getNode' : ActorMethod<[bigint], Node>,
  'getNodes' : ActorMethod<[], Array<Node>>,
  'getPackage' : ActorMethod<[bigint], Package>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getPayment' : ActorMethod<[bigint], Payment>,
  'getPayments' : ActorMethod<[], Array<Payment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAdminAccount' : ActorMethod<[string, string], string>,
  'removeAdminAccount' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];