/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdvanceRechargeDue {
    id: string;
    userName: string;
    createdAt: bigint;
    dueMonth: string;
    serial: bigint;
    address: string;
    mobile: string;
    carnivalId: string;
    dueAmount: number;
}
export type Time = bigint;
export interface Package {
    id: bigint;
    name: string;
    description: string;
    speed: string;
    monthlyPrice: number;
}
export interface Expense {
    id: string;
    date: string;
    createdAt: bigint;
    rate: number;
    unit: string;
    description: string;
    serial: bigint;
    category: string;
    amount: number;
}
export interface Customer {
    id: bigint;
    status: ServiceStatus;
    area: string;
    name: string;
    email: string;
    connectionDate: Time;
    address: string;
    phone: string;
    monthlyFee: number;
    packageId: bigint;
    dueAmount: number;
}
export interface CustomerFinancialOverride {
    connectionFeeCash: number;
    cidNumber: string;
    connectionFeeDue: number;
}
export interface Payment {
    id: bigint;
    month: bigint;
    paymentMethod: string;
    date: Time;
    note: string;
    year: bigint;
    customerId: bigint;
    amount: number;
}
export interface TechnicianSalaryDue {
    id: string;
    technicianName: string;
    createdAt: bigint;
    dueMonth: string;
    serial: bigint;
    totalDue: number;
    dueAmount: number;
}
export interface AdminAccount {
    name: string;
    email: string;
}
export interface Node {
    id: bigint;
    status: string;
    name: string;
    connectedCustomers: bigint;
    location: string;
}
export interface DebtSummary {
    totalPayables: number;
    totalReceivables: number;
}
export interface ConnectionFeeDue {
    id: string;
    userName: string;
    cidNumber: string;
    createdAt: bigint;
    dueMonth: string;
    serial: bigint;
    address: string;
    mobile: string;
    dueAmount: number;
}
export interface CommissionDue {
    id: string;
    commissionSource: string;
    totalCommission: number;
    paidCommission: number;
    createdAt: bigint;
    dueMonth: string;
    serial: bigint;
    outstandingCommission: number;
}
export interface UserProfile {
    name: string;
}
export interface WholesalerDue {
    id: string;
    date: string;
    createdAt: bigint;
    rate: number;
    dueBill: number;
    productName: string;
    serial: bigint;
    paidBill: number;
    totalAmount: number;
    address: string;
    quantity: number;
    mobile: string;
    wholesalerName: string;
    amount: number;
}
export enum ServiceStatus {
    active = "active",
    inactive = "inactive",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminAccount(email: string, password: string, name: string): Promise<void>;
    addAdvanceRechargeDue(record: AdvanceRechargeDue): Promise<void>;
    addCommissionDue(record: CommissionDue): Promise<void>;
    addConnectionFeeDue(record: ConnectionFeeDue): Promise<void>;
    addExpense(expense: Expense): Promise<void>;
    addTechnicianSalaryDue(record: TechnicianSalaryDue): Promise<void>;
    addWholesalerDue(record: WholesalerDue): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAdvanceRechargeDue(id: string): Promise<void>;
    deleteCommissionDue(id: string): Promise<void>;
    deleteConnectionFeeDue(id: string): Promise<void>;
    deleteExpense(expenseId: string): Promise<void>;
    deleteTechnicianSalaryDue(id: string): Promise<void>;
    deleteWholesalerDue(id: string): Promise<void>;
    getAdminAccounts(): Promise<Array<AdminAccount>>;
    getAdvanceRechargeDues(): Promise<Array<AdvanceRechargeDue>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommissionDues(): Promise<Array<CommissionDue>>;
    getConnectionFeeDues(): Promise<Array<ConnectionFeeDue>>;
    getCustomer(id: bigint): Promise<Customer>;
    getCustomerFinancials(): Promise<Array<CustomerFinancialOverride>>;
    getCustomers(): Promise<Array<Customer>>;
    getDebtSummary(): Promise<DebtSummary>;
    getExpenses(): Promise<Array<Expense>>;
    getNode(id: bigint): Promise<Node>;
    getNodes(): Promise<Array<Node>>;
    getPackage(id: bigint): Promise<Package>;
    getPackages(): Promise<Array<Package>>;
    getPayment(id: bigint): Promise<Payment>;
    getPayments(): Promise<Array<Payment>>;
    getTechnicianSalaryDues(): Promise<Array<TechnicianSalaryDue>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWholesalerDues(): Promise<Array<WholesalerDue>>;
    isCallerAdmin(): Promise<boolean>;
    loginAdminAccount(email: string, password: string): Promise<string>;
    removeAdminAccount(email: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAdvanceRechargeDue(record: AdvanceRechargeDue): Promise<void>;
    updateCommissionDue(record: CommissionDue): Promise<void>;
    updateConnectionFeeDue(record: ConnectionFeeDue): Promise<void>;
    updateCustomerFinancial(override: CustomerFinancialOverride): Promise<void>;
    updateExpense(expense: Expense): Promise<void>;
    updateTechnicianSalaryDue(record: TechnicianSalaryDue): Promise<void>;
    updateWholesalerDue(record: WholesalerDue): Promise<void>;
}
import type { Customer as _Customer, ServiceStatus as _ServiceStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminAccount(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminAccount(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminAccount(arg0, arg1, arg2);
            return result;
        }
    }
    async addAdvanceRechargeDue(arg0: AdvanceRechargeDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdvanceRechargeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdvanceRechargeDue(arg0);
            return result;
        }
    }
    async addCommissionDue(arg0: CommissionDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommissionDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommissionDue(arg0);
            return result;
        }
    }
    async addConnectionFeeDue(arg0: ConnectionFeeDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addConnectionFeeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addConnectionFeeDue(arg0);
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return result;
        }
    }
    async addTechnicianSalaryDue(arg0: TechnicianSalaryDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTechnicianSalaryDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTechnicianSalaryDue(arg0);
            return result;
        }
    }
    async addWholesalerDue(arg0: WholesalerDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWholesalerDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWholesalerDue(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAdvanceRechargeDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvanceRechargeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvanceRechargeDue(arg0);
            return result;
        }
    }
    async deleteCommissionDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommissionDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommissionDue(arg0);
            return result;
        }
    }
    async deleteConnectionFeeDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConnectionFeeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConnectionFeeDue(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteTechnicianSalaryDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTechnicianSalaryDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTechnicianSalaryDue(arg0);
            return result;
        }
    }
    async deleteWholesalerDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWholesalerDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWholesalerDue(arg0);
            return result;
        }
    }
    async getAdminAccounts(): Promise<Array<AdminAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAccounts();
            return result;
        }
    }
    async getAdvanceRechargeDues(): Promise<Array<AdvanceRechargeDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvanceRechargeDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvanceRechargeDues();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommissionDues(): Promise<Array<CommissionDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionDues();
            return result;
        }
    }
    async getConnectionFeeDues(): Promise<Array<ConnectionFeeDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionFeeDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionFeeDues();
            return result;
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_Customer_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_Customer_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerFinancials(): Promise<Array<CustomerFinancialOverride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerFinancials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerFinancials();
            return result;
        }
    }
    async getCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebtSummary(): Promise<DebtSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebtSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebtSummary();
            return result;
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getNode(arg0: bigint): Promise<Node> {
        if (this.processError) {
            try {
                const result = await this.actor.getNode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNode(arg0);
            return result;
        }
    }
    async getNodes(): Promise<Array<Node>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNodes();
            return result;
        }
    }
    async getPackage(arg0: bigint): Promise<Package> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackage(arg0);
            return result;
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return result;
        }
    }
    async getPayment(arg0: bigint): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return result;
        }
    }
    async getPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return result;
        }
    }
    async getTechnicianSalaryDues(): Promise<Array<TechnicianSalaryDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechnicianSalaryDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechnicianSalaryDues();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWholesalerDues(): Promise<Array<WholesalerDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWholesalerDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWholesalerDues();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginAdminAccount(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAdminAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAdminAccount(arg0, arg1);
            return result;
        }
    }
    async removeAdminAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminAccount(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAdvanceRechargeDue(arg0: AdvanceRechargeDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdvanceRechargeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdvanceRechargeDue(arg0);
            return result;
        }
    }
    async updateCommissionDue(arg0: CommissionDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCommissionDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCommissionDue(arg0);
            return result;
        }
    }
    async updateConnectionFeeDue(arg0: ConnectionFeeDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConnectionFeeDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConnectionFeeDue(arg0);
            return result;
        }
    }
    async updateCustomerFinancial(arg0: CustomerFinancialOverride): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomerFinancial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomerFinancial(arg0);
            return result;
        }
    }
    async updateExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0);
            return result;
        }
    }
    async updateTechnicianSalaryDue(arg0: TechnicianSalaryDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTechnicianSalaryDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTechnicianSalaryDue(arg0);
            return result;
        }
    }
    async updateWholesalerDue(arg0: WholesalerDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWholesalerDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWholesalerDue(arg0);
            return result;
        }
    }
}
function from_candid_Customer_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceStatus): ServiceStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ServiceStatus;
    area: string;
    name: string;
    email: string;
    connectionDate: _Time;
    address: string;
    phone: string;
    monthlyFee: number;
    packageId: bigint;
    dueAmount: number;
}): {
    id: bigint;
    status: ServiceStatus;
    area: string;
    name: string;
    email: string;
    connectionDate: Time;
    address: string;
    phone: string;
    monthlyFee: number;
    packageId: bigint;
    dueAmount: number;
} {
    return {
        id: value.id,
        status: from_candid_ServiceStatus_n8(_uploadFile, _downloadFile, value.status),
        area: value.area,
        name: value.name,
        email: value.email,
        connectionDate: value.connectionDate,
        address: value.address,
        phone: value.phone,
        monthlyFee: value.monthlyFee,
        packageId: value.packageId,
        dueAmount: value.dueAmount
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    suspended: null;
}): ServiceStatus {
    return "active" in value ? ServiceStatus.active : "inactive" in value ? ServiceStatus.inactive : "suspended" in value ? ServiceStatus.suspended : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
